### ISSUE TITLE
Add Wisconsin closure form

### ISSUE THREAD

**Issue by crazycaveman** [WazeDev/WME-Form-Filler#5]
ojlaw requested WI added to the script.

[Pre-filled link](https://docs.google.com/forms/d/e/1FAIpQLSeiKY0KsO0xN69Asw77MARQFmxOy6zQXF-k2OQdWOfwtiCp7Q/viewform?entry.1204781462=ojlaw&entry.828228572=CLOSED&entry.1647952662=Test1&entry.1501712688=Test2&entry.2094306654=Test3&entry.1414240321=One-Way&entry.900957975=00/00/0000+00:00&entry.1051351191=Adams&entry.1093044522=Test4&entry.1540676081=City&entry.430378754=Test5&entry.1754051160=Test6&entry.172235277=Test7&entry.1722909714=Test8)
[Sheet](https://docs.google.com/spreadsheets/d/1byVE5EIZqoxNsqocpa3v4aJfnWaG4hRzKxWVdxTyMfY/edit)

**Comment by ojlaw** [comment]
thank you for looking into this!
